export type Workflow44Reference = {
    url: string;
    weight: 0;
    categories: string[];
};

export type Workflow44Payload = {
    toolsetEntry: 1;
    toolsetLv2: 'explore';
    model: 39;
    'referenceUploadGroup-container': true;
    'prompt-container': true;
    __generationSettings: { exploreV3: Record<string, never> };
    megapixels: 1;
    baseImage: string;
    referenceImage: Workflow44Reference[];
    imageType: string;
    workflowId: 39;
    workflowVersion: 'V3';
    enteredText: string;
    additionalPrompt: string;
    designLibraryName: 'No Style';
    designLibraryId: 99;
    firstTierName: 'No Style';
    firstTierId: 9999;
    secondTierName: 'No Style';
    secondTierId: 9999;
    styleId: 9999;
    cameraViewName: 'No Camera';
    cameraViewId: 9999;
    graphicStyleId: 9999;
    atmosphereId: 99;
    atmosphereType: '';
    orientation: -2;
    imageRatio: -2;
    additionalNegativePrompt: '';
    inputFidelityLevel: 0;
    controlLevel: 0;
    maskImage: '';
    originalImage: '';
    horizontalPercentage: 0;
    verticalPercentage: 0;
    firstFrame: '';
    imageTail: '';
    videoPrompt: 0;
    timeLapse: 0;
    cameraSpeed: 0;
    projectId: number;
    projectName: string;
    teamId: number;
    prompt: string;
    privateModel: '';
    height: 816;
    width: 1456;
    quality: 'medium';
    angleIndex: 0;
    imageCount: 1;
    language: 'en' | 'chs';
};

export type JobState = { status: string; message?: string };
export type GenerationOutput = {
    mediaId?: number | string;
    url: string;
    thumbnail?: string;
    width?: number;
    height?: number;
    createdAt?: string;
    [key: string]: unknown;
};
export type GenerationResult = { outputs: GenerationOutput[] };
